version: '3'
# image names have been appended with the ACR name
# (there's a bug in azure web-apps and it needs the ACR name in the image name)

services:
  
  backend:
    image: isukinrepo.azurecr.io/fapi-azure-backend:latest
    restart: always
    build:
      context: ./backend
      args:
        INSTALL_DEV: 'false'
    
  frontend:
    image: isukinrepo.azurecr.io/fapi-azure-frontend:latest
    restart: always
    build:
      context: ./frontend
      args: 
        - NODE_ENV=production
    depends_on:
      - backend
    ports:
      - 80:80
    
volumes:
  app-db-data:
