apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: fapi-azure-frontend:latest 
        imagePullPolicy: Never
        # kind load docker-image fapi-azure-frontend:latest
        # ..jesus: https://iximiuz.com/en/posts/kubernetes-kind-load-docker-image/
        # need to repeat this in every yaml file:
        env:
        - name: FRONTEND_API_TARGET
          valueFrom:
            secretKeyRef:
              name: fapi-secrets
              key: FRONTEND_API_TARGET
        - name: PROJECT_NAME
          valueFrom:
            secretKeyRef:
              name: fapi-secrets
              key: PROJECT_NAME
        - name: DOMAIN
          valueFrom:
            secretKeyRef:
              name: fapi-secrets
              key: DOMAIN
        - name: ENVIRONMENT
          valueFrom:
            secretKeyRef:
              name: fapi-secrets
              key: ENVIRONMENT
        - name: BACKEND_CORS_ORIGINS
          valueFrom:
            secretKeyRef:
              name: fapi-secrets
              key: BACKEND_CORS_ORIGINS
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: fapi-secrets
              key: SECRET_KEY
        - name: FIRST_SUPERUSER
          valueFrom:
            secretKeyRef:
              name: fapi-secrets
              key: FIRST_SUPERUSER
        - name: FIRST_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fapi-secrets
              key: FIRST_SUPERUSER_PASSWORD
        - name: USERS_OPEN_REGISTRATION
          valueFrom:
            secretKeyRef:
              name: fapi-secrets
              key: USERS_OPEN_REGISTRATION
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: fapi-secrets
              key: SMTP_HOST
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: fapi-secrets
              key: SMTP_USER
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fapi-secrets
              key: SMTP_PASSWORD
        - name: EMAILS_FROM_EMAIL
          valueFrom:
            secretKeyRef:
              name: fapi-secrets
              key: EMAILS_FROM_EMAIL
        - name: POSTGRES_SERVER
          valueFrom:
            secretKeyRef:
              name: fapi-secrets
              key: POSTGRES_SERVER
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: fapi-secrets
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: fapi-secrets
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: fapi-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fapi-secrets
              key: POSTGRES_PASSWORD
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: fapi-secrets
              key: SENTRY_DSN
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
